name: ServerLoveMCPE
main: ServerLoveMCPE\Main
version: 3.2.4
api: [3.9]
load: POSTWORLD
author: TheDeibo
description: Add a little romance to your server!
commands:
 serverlove:
  description: §aDisplays Plugin Infomation
  usage: "§a/serverlove."
  aliases: [sl, loveserver]
  permission: serverlovemcpe.serverlove
 love:
  description: §a Love a player
  usage: "§a/love <playerName>"
  aliases: [l, fancy, marry, propose]
  permission: serverlovemcpe.love
 breakup:
  description: §a Love a player
  usage: "§a/breakup <playerName>"
  aliases: [break, dump]
  permission: serverlovemcpe.breakup
  permission: serverlovemcpe.breakup
 nolove:
  description: §aToggle if you want to / dont want to love.
  usage: "§a/nolove <nolove | love>"
  aliases: [nl]
  permission: serverlovemcpe.nolove
permissions:
 serverlovemcpe.serverlove:
  description: "§aDisplays Plugin Infomation"
  default: true
 serverlovemcpe.love:
  description: "§aAllows the user to love another player"
  default: true
 serverlovemcpe.breakup:
  description: "§aAllows the user to breakup with another player"
  default: true
 serverlovemcpe.nolove:
  description: "§aAllows the user to be / not to be loved."
  default: true
